name: 友链模板
description: 提交友链意向申请。
labels: ['审核中']
body:
  - type: textarea
    id: json-data
    validations:
      required: true
    attributes:
      label: 友链信息
      description: 请在双引号中填写，不要修改格式。
      value: |
        <!--
        请在下方的 `JSON` 块中填写，字段说明：
        - title: 友链标题
        - url: 友链地址
        - icon: 网站图标
        - snapshot: 网站截图
        - description: 一句话简介
        - feed: 订阅地址（抓取并显示最新文章，没有 feed 地址时，排序会靠后）
        -->
        
        ```json
        {
            "title": "",
            "url": "",
            "icon": "",
            "snapshot": "",
            "description": "",
            "feed": ""
        }
        ```

        
  - type: input
    id: friends-html
    attributes:
      label: 友链地址
      description: 请输入您的友链页面地址，用于人工审核和 GitHub Actions 自动检测。（不必提前添加本站为友链，审核通过后再添加也不迟。）
      placeholder: "如: https://xaoxuu.com/friends/"
    validations:
      required: true
